### ISSUE TITLE
randomize worker-id

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/worker-service#10]
Radomize worker ids, so worker-service requests cannot be spammed to lower or higher worker id´s

**Comment by LeanderK** [comment]
scheduled for next db-iteration

**Comment by phimonk** [comment]
I'm not sure if this is still necessary after we implemented JWT.
Because then all requests are checked for their authentication header, which also contains the signed workerId. We could even go so far and remove all references to the workerId in the calls and rely completely on the JWT.

**Comment by LeanderK** [comment]
i was not taking the issue literally. When i close the security issue, i'll close the issue. I am not so sure about JWT, but it is definity an option.
