### ISSUE TITLE
Error no PlatformMode for Platform, when trying to post email

### ISSUE THREAD

**Issue by phimonk** [coolcrowd/worker-service#11]
When trying to post an email for a worker this [error](https://gist.github.com/phimonk/0aa599ec06be1029b402) occurs in worker-service.

The table Experiments_Platform_Mode is empty.

**Comment by LeanderK** [comment]
Whats in your Experiments_Platform_Mode and Experiments_Platform table?

**Comment by LeanderK** [comment]
should be fixed with 9cdb88c0a021115e602ea2e2ed29b5e3636e1547

**Comment by LeanderK** [comment]
@phimonk can you confirm the fix?

**Comment by phimonk** [comment]
fix confirmed
