### ISSUE TITLE
Workers that don't have the needed calibrations are forwarded to answers

### ISSUE THREAD

**Issue by phimonk** [coolcrowd/worker-service#14]
The worker-service should respond with `FINISHED` if the worker does not have the needed calibrations to access the task. Instead all workers are presented the `ANSWER` view.

**Comment by LeanderK** [comment]
hmm thats more tricky, i need a log

**Comment by phimonk** [comment]
There is no exception. But it seems as there is another bug in OS.
The OS always returns 
>DEBUG e.k.i.c.w.c.Commands - Object service answered with OK.
no matter what calibration option was selected.

If object service returned okay, shouldn't the worker be forwarded to the next view?

Furthermore it is possible to post another answer to the same calibration. resulting in workers having all answer options selected

**Comment by LeanderK** [comment]
i am debugging this right now, some strange things are happening ;)

**Comment by phimonk** [comment]
beautiful :)
