### ISSUE TITLE
Preview returns finish

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/worker-service#18]
When a preview should be displayed FINISH is sent back, (not sure if the misstake is in the ui or here)

**Comment by LeanderK** [comment]
this is intended,this made it really easy to implemented preview

**Comment by marcelhollerbach** [comment]
@phimonk so its you :smiling_imp:

**Comment by phimonk** [comment]
uuuum, im pretty sure we said, that ws should return the the answerview for preview. 
To display the finished view doesn't make any sense as their is no information to display.

**Comment by LeanderK** [comment]
no, it just passes all the information needed, but i can turn it into an answer-type
