### ISSUE TITLE
Common config

### ISSUE THREAD

**Issue by kelunik** [coolcrowd/worker-service#2]
There should be one common config for the `worker-service` and `object-service` if possible.

**Comment by LeanderK** [comment]
no

**Comment by LeanderK** [comment]
i don't think so, they are different system that scale different

**Comment by kelunik** [comment]
There are indeed different settings. Maybe we can just make the config format the same.

**Comment by marcelhollerbach** [comment]
I think we can close this as wontfix.

**Comment by LeanderK** [comment]
confirm
