### ISSUE TITLE
calibrations are not working anymore...again

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/worker-service#34]
selecting valid values leads to being excluded

**Comment by LeanderK** [comment]
i can't reproduce it

**Comment by marcelhollerbach** [comment]
Talking with yourself ? :P

**Comment by LeanderK** [comment]
was reported by @phimonk Can you reproduce it?

**Comment by marcelhollerbach** [comment]
works fine here ...

**Comment by LeanderK** [comment]
yeah! the query is more complicated the you would think!
